/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DevOpsBuild;

import com.google.common.net.InternetDomainName;
import com.mitchtalmadge.asciidata.graph.ASCIIGraph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        InternetDomainName owner =
        InternetDomainName.from("devops.zhaw.ch").topPrivateDomain(); // returns zhaw.ch
        boolean valid = InternetDomainName.isValid("takipi.monsters"); // return false

        System.out.println(owner.toString());
        System.out.println("valid:" + valid);


        String graph = ASCIIGraph.fromSeries(new double[] { 1.0, 2.0, 3.0, 10.0, 7.0, 9.0, 5.0, 4.0 }).plot();  
        System.out.println(graph);
    }
}
